name: Test

on:
  push:
    branches:
      - 'master'
  # pull_request:

jobs:
  build:

    runs-on: "ubuntu-20.04"

    steps:

    - uses: actions/checkout@v2

    - name: setup env
      run: echo ${{ secrets.PROPS }} > .env

    - name: copy files to host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOST_PORT || 22 }}
        source: "."
        target: "app"

    - uses: actions/checkout@v2

    - name: build app in host
      uses: appleboy/ssh-action@v0.1.8
      with:
        debug : true
        timeout : '250s'
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOST_PORT || 22 }}
        script: /bin/bash -c -i 'cd app && npm i && npm start'